In [1]:
import tensorflow as tf

In [2]:
###======================================= assign value  ===================================#

a = tf.ones([2,3])
# a is 2 X 3  all variable one Tensor
print(a)

# a[0,0] = 10 => TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

a = tf.Variable(a)
a[0,0].assign(10)
b = a.read_value()
print(b)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[10.  1.  1.]
 [ 1.  1.  1.]], shape=(2, 3), dtype=float32)


In [20]:
a = tf.zeros([10,5])
b = tf.Variable(a)

#a.numpy() == b.numpy()
a[0,0].numpy()

#a[0,0]= 10 # This will cause Error 
# Tensor Flow does not support item assignment
# In Generally we dont need item assignment
b[0,0].assign(10)

#a[0,0].assign(10)
a = tf.Variable(a) #Need to change to variable
a[0,0].assign(25)
#a.numpy()

<tf.Variable 'UnreadVariable' shape=(10, 5) dtype=float32, numpy=
array([[25.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]], dtype=float32)>

In [47]:
a = tf.constant(10)
b = tf.constant(20)
print((a+b).numpy())
print(a.numpy()+b.numpy())
print("Addition with Function", tf.add(a,b).numpy())
# *****************************************************
print("Multiplication With constant",(a*b).numpy())
print(np.add(a,b))
print(np.multiply(a,b))
print("Multiplication with Function",tf.multiply(a,b).numpy())
a = tf.constant([[3,3]])
print(a.numpy().shape)
# Create a tensor of 2x2
b = tf.constant([[3,3],[4,4]])
print(a.numpy().shape)

# Doing tensor function matmul()
# Matrix Multiplicatino is different
result = tf.matmul(a,b)
print(result.numpy())

# Broad Cast Matrix in Multiplication
print(a *b) # Element wise operation


30
30
Addition with Function 30
Multiplication With constant 200
30
200
Multiplication with Function 200
(1, 2)
(1, 2)
[[21 21]]


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9,  9],
       [12, 12]])>

In [4]:
###===================================== cast operations =====================================#

a = tf.convert_to_tensor(2.)
b = tf.cast(a, tf.int32)
print(a, b)

tf.Tensor(2.0, shape=(), dtype=float32) tf.Tensor(2, shape=(), dtype=int32)


In [57]:
## tf.cast 
# Casts a  tensor to new type
tf.cast(a, tf.int32).numpy()

###### Tensor Flow Shape Operation
a = tf.ones([2,3])
print(a.shape)
shape = tf.shape(a)
print(shape[0])
print(shape[1])


(2, 3)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
